from enum import Enum


class ErrorCode(str, Enum):
    SERVICE_NOT_READY = "SERVICE_NOT_READY"
    NO_CLINICAL_TRIALS = "NO_CLINICAL_TRIALS"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_QUERY = "INVALID_QUERY"
